### ISSUE TITLE
Update Accounts creation to store the Customers Id

### ISSUE THREAD

**Issue by SanGeeky** [kommitters/mintacoin#109]
ℹ️ This issue is part of Epic #69 

## Objective

Add a new relationship where `Customers` has many `Accounts`, therefore the `Account` schema will be:
```elixir
%{
   id: UUID # Key to identify a blockchain event within the table
   address: string # ed25519 public key for payments 
   encrypted_signature: string # ed25519 SK of the account in mintacoin encrypted with an entropy (12 words) 
   customer_id: string # This is the ID of the customers that creates this Account
}
```

* Update the migrations
* Create the index for the `customer_id`.
* Update the changeset of Accounts.

## Checklist
- [x] Update the `Account` schema which will belong to a `Customer`. 
- [x] Update the test suite.

**Comment by samu975** [comment]
Hello, can I work on this issue?

**Comment by samu975** [comment]
Hi, can I work on this issue?
