### ISSUE TITLE
Add API versioning to Mintacoin's endpoints 

### ISSUE THREAD

**Issue by SanGeeky** [kommitters/mintacoin#113]
### Is your feature request related to a problem? 

Before launching Mintacoin's MVP, it is required to use API versioning for all endpoints.

### Describe the solution you'd like

1. The current scope should contain a prefix with `/v1-alpha` in the router. Therefore all the requests will look like this:

 ```http
POST /v1-alpha/accounts
GET  /v1-alpha/assets/:id
POST /v1-alpha/accounts/:address/assets/:asset_id/trust
```

2. Also, we need to add an index endpoint and display a user-friendly message with Mintacoin's information, for example

> Welcome to Mintacoin :coin: 
The minimalist and open-source API to abstracts the blockchain complexity by providing a simple and reliable infrastructure layer to mint your crypto assets and process payments with them.
>
> Check out our documentation at https://docs.mintacoin.co/.

3. Finally, the index endpoint for `/v1-alpha` should redirect to the main index `/`

### Additional context

- https://cloud.google.com/apis/design/versioning?hl=en

**Comment by juanm-roa** [comment]
Hi! can I work on this issue?
