### ISSUE TITLE
Create tests for the Stellar implementations

### ISSUE THREAD

**Issue by SanGeeky** [kommitters/mintacoin#114]
ℹ️ This issue is part of Epic #55 

## Objective

We need to increase the test coverage for the Stellar implementation, currently, the test coverage for these files is 0%, therefore is required to add a new test suite for the following files:

- `lib/mintacoin/accounts/crypto/stellar.ex`
- `lib/mintacoin/assets/crypto/stellar.ex`
- `lib/mintacoin/payments/crypto/stellar.ex`

Take into account that these modules make an API request to Horizon, which is the client used by Stellar, and for testing purposes, we need to make a Canned Implementation for the responses. To complete follow these steps:

1. Replace the Horizon Transactions with a function that returns the correct module depending on the environment:

    ```elixir
    # Current Code
    Horizon.Transactions.create()
     
    # Replaced by
    horizon_client().create()
    
    @spec horizon_client :: atom()
    defp horizon_client do
      Application.get_env(:mintacoin, :horizon, Horizon.Transactions)
    end
    ```

2. In the test config add the following application variable:
    `config :mintacoin,  horizon: Horizon.CannedTransactions`

3. Within the test suite creates a module called `Horizon.CannedTransactions` which contains the function  `create/1` and returns the expected response from Horizon, similar to the result of a transaction. It is possible to create this Transaction response with Mocks.

## Checklist

- [x] Update the Horizon implementation.
- [x] Add the canned implementation.
- [x] Create the test suite.

**Comment by samu975** [comment]
Hello, can I work on this issue?

**Comment by AndresRamirez9912** [comment]
Hi, can I work on this issue?
