### ISSUE TITLE
Implement the endpoints to create payments

### ISSUE THREAD

**Issue by CristhianRodriguezMolina** [kommitters/mintacoin#117]
ℹ️ This issue is part of Epic #66 

## Objective

Implement in the context of mintacoin web, the endpoints related to payments:

- Create a payment between two accounts.

``` 
POST https://sandbox.api.mintacoin.co/v1-alpha/payments
```

## Checklist

- [ ] Create the endpoint in the router for payments.
- [ ] Create the view and controller.

**Comment by juanm-roa** [comment]
Can i work on this issue?
