### ISSUE TITLE
Update the API home landing

### ISSUE THREAD

**Issue by CristhianRodriguezMolina** [kommitters/mintacoin#130]
### Describe the solution you'd like

We need to modify the temporal landing made for the home or root (`/` or `/v1-alpha`) in the mintacoin API, in order to redirect this home to the Mintacoin API documentation: https://docs.mintacoin.co/

### Describe alternatives you've considered

- [x] Add in the router the configuration to route to https://docs.mintacoin.co/ when accessing the API home (`/` or `/v1-alpha`).
- [x] Remove the templates and all the unnecessary files from the previous home landing.

**Comment by FelipeGuzmanSierra** [comment]
Hi, can I work on this issue?
