### ISSUE TITLE
Using `Application.compile_env!/3` throw an error when deploying

### ISSUE THREAD

**Issue by CristhianRodriguezMolina** [kommitters/mintacoin#134]
### Precheck

- [x] Do a quick search and make sure the bug has not been reported yet.
- [x] Please disclose security vulnerabilities privately at [oss@kommit.co](mailto:oss@kommit.co).
- [x] Finally, be nice and have fun!.

### Description

We are getting an env var in the `lib/mintacoin/accounts/crypto/stellar.ex` file with the `Application.compile_env!/3` function but this function is throwing an error when deploying Mintacoin to fly.io.

### Environment

* Operating system: Linux 21 Vanessa 2022.

### Current behavior

![image](https://user-images.githubusercontent.com/50219561/202796728-9366761f-f15d-4338-b614-567080f3c2a0.png)

### Expected behavior

![image](https://user-images.githubusercontent.com/50219561/202797084-6f4bd88e-3f12-47a5-a10a-e732d8abad75.png)

**Comment by FelipeGuzmanSierra** [comment]
Hi, can I work on this issue?
