### ISSUE TITLE
Keypairs generation for accounts

### ISSUE THREAD

**Issue by peterchicaiza** [kommitters/mintacoin#25]
ℹ️ This issue is part of the epic #28

### Describe the solution you'd like

To generate a keypairs set.

### Describe alternatives you've considered
To generate a public-key based on [public-encrypt](https://www.erlang.org/doc/man/crypto.html#public_encrypt-4)
To generate a secret-key based on [crypto](https://www.erlang.org/doc/man/crypto.html) algorithms

**Comment by peterchicaiza** [comment]
## Research Update
After the research of available modules and libraries for encrypting with Elixir, it was decided to implement the functions given by the `:crypto` module, the erlang module that compiles several functions for encrypting, hashing, and keys generation.

### Functions to implement:

- #### strong_rand_bytes/1
  Generates N bytes randomly uniform 0..255, and returns the result in a binary
  ```elixir
     :crypto.strong_rand_bytes(16) # We will be using random binaries of 16 bytes
  ```

- #### crypto_one_time
  Given a cipher algorithm(`cipher`), an initialization vector(`iv`) a secret key and the text to encrypt(`payload`) it operates a one time encryption on the given text.
  ```elixir
    payload = "Text to be encrypted"
    cipher = :aes_128_cbc
    iv = :crypto.strong_rand_bytes(16)
    secret_key = :crypto.strong_rand_bytes(16)

     ciphertext =
        cipher
        |> :crypto.crypto_one_time(secret_key, iv, payload, true)
        |> (&(iv <> &1)).()
        |> Base.encode64(padding: false)
  ```

- #### hash
  Computes the data using the given type.

  ```elixir
     :crypto.hash(:sha256, data_to_hash)
  ```

- #### generate_key/2
  In order to generate a keypair, it is required to define the cipher algorithm and the parameters for this algorithm. Due to its lightness and cheap generation, we will be using as cipher algorithm `:ddsa` with the `:ed25519` curve.
  ```elixir
    
    {pub, priv} = :crypto.generate_key(:eddsa, :ed25519)
    public_key = Base.encode64(pub, padding: false)
    private_key = Base.encode64(priv, padding: false)
  ```

**Comment by miguelnietoa** [comment]
## Research Update

In the Encryption default module, we need to change the `cipher` from `aes_128_cbc` to `aes_256_cbc`.

### Why?
The keypairs generated by the `:crypto` module have a byte length of 32, so it means that we need `32 * 8 = 256` bits to represent the secret key that will be used to encrypt the secrets from the Blockchain implementations. 

That's why a change in the cipher is needed, and `aes_256_cbc` is the right one. 

### Before: (cipher: `aes_128_cbc`)
```elixir
iex> {:ok, {pub, sec}} = Mintacoin.Keypair.random                          
{:ok,         
 {"E6BK96B84IQ678F4BQLMRP3GGN4H8NBTIFCADJ05C4JOK072AIUG",
  "eQcGN/+cGgiplgA7gZj+H0snXWh36byomVGM+lFubpQ"}}
iex> Mintacoin.Encryption.encrypt("STELLARSECRETKEY", sec)
{:error, :encryption_error}
```

### After: (cipher: `aes_256_cbc`)

```elixir
iex> {:ok, {pub, sec}} = Mintacoin.Keypair.random                          
{:ok,         
 {"E6BK96B84IQ678F4BQLMRP3GGN4H8NBTIFCADJ05C4JOK072AIUG",
  "eQcGN/+cGgiplgA7gZj+H0snXWh36byomVGM+lFubpQ"}}
iex> Mintacoin.Encryption.encrypt("STELLARSECRETKEY", sec)
{:ok, "JUKdVcSXF49rvi/oecBeSs3dTZFwd9Yi3QV8zqmkm/7uSW1AbVSzWqocVu/ZAD4b"}
```
