### ISSUE TITLE
Dockerize local setup

### ISSUE THREAD

**Issue by CristhianRodriguezMolina** [kommitters/mintacoin#53]
### Describe the solution you'd like

Dockerize the local setup of Mintacoin.

### Describe alternatives you've considered

- [ ] Dockerize the local setup an ensure the correct functioning.

**Comment by keliumJU** [comment]
Hello, I would like to take care of this issue

**Comment by SanGeeky** [comment]
@keliumJU Got for it, I'll assign this issue to you. 

Currently, we have a `Dockerfile` with the docker instructions for production, we need to dockerize the setup for the development instances. As you advance with the Issue, you can create a draft PR to help you before the PR is ready for review.

**Comment by keliumJU** [comment]
Hello, I think the pull request has already been sent, I had never done one in an open-source project, so I'll make sure. https://github.com/kommitters/mintacoin/pull/81
