### ISSUE TITLE
Refactor errors from controllers and use a fallback strategy.

### ISSUE THREAD

**Issue by SanGeeky** [kommitters/mintacoin#60]
ℹ️ This issue is part of Epic #55

## Objective

Remove the function that returns error messages within the controllers created until now, in addition to this you must refactor the functions which contain errors in the views. Up next you will find some examples

```elixir
  # lib/mintacoin_web/controllers/accounts_controller.ex
  defp handle_response({:error, resource}, _conn, _status, _template) do
    {status, message} = Map.get(@errors, resource, {400, "Accounts Controller Error"})

    {:error, %{status: status, detail: message, code: resource}}
  end
```

These resulting errors should be handled by the plug `fallback_controller.ex`.

Also, we need to update the views for rendering errors, the current implementation contains functions that render the errors from each controller, for example:

```elixir
# lib/mintacoin_web/views/accounts_view.ex
def render("error.json", %{error: %{status: status, code: code, detail: detail}}),
    do: %{status: status, code: code, detail: detail}
```

These errors should be handled in the file `error_view.ex`.

Review the following documentation for more information:
*  [Put View
](https://hexdocs.pm/phoenix/Phoenix.Controller.html#put_view/2)
* [Action Fallback
](https://hexdocs.pm/phoenix/Phoenix.Controller.html#action_fallback/1)

## Checklist

- [ ] Remove the errors from the controllers.
- [ ] Put the errors to be managed in the fallback controller.
- [ ] Move the errors to be managed in the error_view.

**Comment by samu975** [comment]
Hello. I want to work on this issue please.

**Comment by SanGeeky** [comment]
@samu975 I will assign this Issue to you, go for it! If you need more information, feel free to ask :)

**Comment by keliumJU** [comment]
Hello, I would like to take care of this issue

**Comment by SanGeeky** [comment]
Hello @keliumJU, go for it! Please keep your branch updated with the feature branch `v0.3`, and mention this Issue when you submit the PR.
