### ISSUE TITLE
Remove the UUID validation with regex from the schemas.

### ISSUE THREAD

**Issue by SanGeeky** [kommitters/mintacoin#63]
ℹ️ This issue is part of Epic #55

## Objective

Remove all `validate_format/3` functions with UUID validations from the schemas.

The current implementation has defensive programming which in the future maybe will not display errors that may occur. 

Remove all the validation from the schemes chainsets like below:
```elixir
|> validate_format(:account_id, @uuid_regex, message: "account_id must be a uuid")
|> validate_format(:blockchain_id, @uuid_regex, message: "blockchain_id must be a uuid")
```

## Checklist

- [x] Remove the UUID validation from all the schemas.
- [x] Remove the tests related to this validation.

**Comment by Odraxs** [comment]
Hello, I would like to be assigned to this issue.
