### ISSUE TITLE
Update field names from schemas which contains associations 

### ISSUE THREAD

**Issue by SanGeeky** [kommitters/mintacoin#65]
ℹ️ This issue is part of Epic #55

## Objective

To improve the code readability we need to update the schemas which contain associations between schemas, for example, the schema `BlockchainTx` contains an association with the schema `Blockchain`, but is represented as follows:

`blockchain_id: Blockchain.t()`

In this relationship, actually, is storing the Blockchain element not only Blockchain ID, therefore is required to update all the similar relations, eg:

- From `blockchain_id: Blockchain.t()` to `blockchain: Blockchain.t()`

## Checklist

- [ ] Identify all associations with the incorrect definition.
- [ ] Update the field names.
- [ ] Update the related tests.

**Comment by samu975** [comment]
Hello. I Want to work on this issue, please.

**Comment by SanGeeky** [comment]
@samu975 I'll assign this issue to you, FYI I just updated the issue description.

**Comment by SanGeeky** [comment]
This issue will be closed due to a misunderstanding definition of the schemas and their associations.
