### ISSUE TITLE
Use bearer token as an authentication mechanism

### ISSUE THREAD

**Issue by juanhurtado10** [kommitters/mintacoin#73]
ℹ️ This issue is part of Epic #55

## Objective
Use a Bearer token as an authorization mechanism for the API.

## Checklist
- [x] Remove the custom `auth-token` from the request header
- [x] Use a standard bearer token instead
- [x] Update the test suite

**Comment by samu975** [comment]
Can I work on this issue ?

**Comment by SanGeeky** [comment]
@juanhurtado10 @CristhianRodriguezMolina after researching the usage of bearer tokens, I think we should implement this functionality in #69, to assign a bearer token to each user. Because the implementation made in #77 just adds the string "Bearer" to the current implementation.

**Comment by juanhurtado10** [comment]
@SanGeeky IMO, this implementation does not affect #77 as it is updating the Plug. So, we can connect clients with their api_token seamlessly.
