### ISSUE TITLE
Update target of continuos delivery workflow

### ISSUE THREAD

**Issue by SanGeeky** [kommitters/mintacoin#80]
:information_source: This issue is part of the Epic #55 

## Objective
The current CD workflow has an issue related to the event when the workflow is triggered
```
on:
  push:
    branches: "v0.2"
```
The correct event should be when a release is published, so is required to update it.

- Checkout this [documentation](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows) 

## Checklist

- [ ] Update the event that trigger the CD workflow

**Comment by jhonatan-kmt** [comment]
I'm going to work on this issue
