### ISSUE TITLE
Add API documentation for assets.

### ISSUE THREAD

**Issue by SanGeeky** [kommitters/mintacoin#84]
ℹ️ This issue is part of Epic #34 

## Describe the solution you'd like
We need to add the API documentation about the changes in version v0.3.0`, specifically with the assets feature.

**Asset Endpoints**
- Create an Asset
- Get an Asset
- Get an asset issuer
- Get the accounts associated with an asset

**Asset Trustline Endpoints**
- Create an asset trustline
- Get assets associated with an account

## Describe alternatives you've considered

- [ ] Add the documentation about the assets endpoints added.

**Comment by jhonatan-kmt** [comment]
Hello, I would like to work on this issue
