### ISSUE TITLE
Implement the customer's database boundaries and functions

### ISSUE THREAD

**Issue by SanGeeky** [kommitters/mintacoin#85]
ℹ️ This issue is part of Epic #69 

## Objective

Create the customer's schema and database functions.

* Create the schema for assets based on the model:
```elixir
%{
   id: UUID # ID
   email: string # customer's email
   name: string # customer's name
   encrypted_api_key: string # Encrypted token with a System ENV for security
}
```
* The context module should be named `Customers`.
* Create customer functions that allow: 
  * creating a new customer.
  * Retrieving their customer info by its id.
* Create the respective migrations.
* Validate `email` as unique.
* Generate the `UUID` for the data payload signed in the token.
* Add the `secret_key_base` and `signing _salt` using the `mix phx.gen.secret 32`.
* Use the encryption functions to encrypt the token.
* The token must contain the customer id information.
* Add a token verification function.

## Checklist

- [ ] Create the `Customer` schema.
- [ ] Add the `Customers` functions.
- [ ] Add the initial test suite for this new context.

**Comment by samu975** [comment]
Hello, can I work on this issue?
