### ISSUE TITLE
Update the API authorization used by customers

### ISSUE THREAD

**Issue by SanGeeky** [kommitters/mintacoin#86]
:information_source:  This issue is part of Epic #69 

## Objective
Currently, the API authorization is made by a static value defined in the configuration of the application, and sharing this value with our clients will take us to security branches, inefficient client management, and bad architecture practices. Therefore are required to update the way we authorize API access with the following requirements:

- Create the functions for the creation and validation of Tokens.
- Add a new Plug for this implementation.
- Ensure adding the `customer_id` value through the `conn`, using the assigns.
- Use the `customer_id` value for the creation of accounts.
- Update the test suite.

## Checklist

- [x] Create the Plug for the API authorization.
- [x] Add the plug to endpoints.
- [x] Add and use the `customer_id` value contained in the Api token.

**Comment by FelipeGuzmanSierra** [comment]
Hello, can I work on this issue?

**Comment by samu975** [comment]
Hello, can I work on this issue?
