### ISSUE TITLE
Update the API REST documentation

### ISSUE THREAD

**Issue by SanGeeky** [kommitters/mintacoin#87]
ℹ️ This issue is part of Epic #69 

## Objective
We need to add the API documentation about the customer's features and the authorization to access API.

## Checklist

- [x] Add the documentation about the customer endpoints added.
- [x] Update for the API token authorization.

**Comment by samu975** [comment]
Hello, can I work on this issue?

**Comment by CristhianRodriguezMolina** [comment]
The API documentation update is already deployed on https://docs.mintacoin.co/, the documentation now is being managed outside the repo, so future changes will be managed only in Gitbook.
