### ISSUE TITLE
Update test suite for the create account worker

### ISSUE THREAD

**Issue by SanGeeky** [kommitters/mintacoin#88]
ℹ️ This issue is part of Epic #55 

## Objective
We need to adjust some tests and create new ones for the following file:

| File | Coverage |
| ----  | ---- |
| `lib/mintacoin/accounts/workers/create_account.ex` | 50% |

The current tests are not complete and we need to add more test cases and update the resulting mocks, you can base this on the test implemented in `test/mintacoin/assets/workers/create_asset_test.exs`.

## Checklist

- [x] Add more test cases and update the mocks.
- [x] Increase the test coverage of the file.

**Comment by juanm-roa** [comment]
I would like to work on this issue.

**Comment by samu975** [comment]
Hello, can I work on this issue?

**Comment by CristhianRodriguezMolina** [comment]
This issue will be closed because its expected result is already fulfilled.
