### ISSUE TITLE
Implement the payment creation with the Stellar SDK

### ISSUE THREAD

**Issue by SanGeeky** [kommitters/mintacoin#95]
ℹ️ This issue is part of Epic #66 

## Objective

To create a payment between accounts is required to check the signatures of the accounts and create a payment operation. Please refer to the Stellar SDK for more information:

> Payment: https://hexdocs.pm/stellar_sdk/0.3.0/payments.html

Remember the actors in this operation:
- Source Account
- Destination Account
- Asset, asset issuer, and amount

You need to sign the transaction with the source account and review if both accounts hold the asset.

> You can base on the stellar implementation to create accounts to do this implementation:
> https://github.com/kommitters/mintacoin/blob/main/lib/mintacoin/accounts/crypto/stellar.ex

## Checklist

- [ ] Implement the payment of an asset operation between accounts using the stellar SDK.

**Comment by juanm-roa** [comment]
I would like to work on this issue.
