### ISSUE TITLE
Implement the payment worker and aggregate functions

### ISSUE THREAD

**Issue by SanGeeky** [kommitters/mintacoin#97]
ℹ️ This issue is part of Epic #66 

## Objective

Create the worker that will perform the database operations and stellar blockchains transactions, to create a payment between Mintacoin accounts.

> You can base on the worker done to create accounts: 
> https://github.com/kommitters/mintacoin/blob/main/lib/mintacoin/accounts/workers/create_account.ex

## Checklist

- [x] Create the function to create the payment and insert the oban job to the queue, we need to validate if the destination account has a `trustline` with the asset of the payment.
> You can base on the `create/1` function from the accounts functions:
> https://github.com/kommitters/mintacoin/blob/main/lib/mintacoin/accounts/accounts.ex
- [x] The worker should receive a map with the following parameters:
  - `source_signature`
  - `source_wallet_id`
  - `detination_wallet_id`
  - `blockchain_id`
  - `asset_id`
  - `amount`
- [x] Process the transaction and create the blockchain tx with the response and the payment_id.
- [x] Validate that the destination account is the Asset Holder of the asset to pay.
- [x] Validate that the source account has enough funds for the asset to pay.
- [x] Update the status of the payment record.
- [x] Update the wallet balances from the actor's accounts.

**Comment by Odraxs** [comment]
I would like to be assigned to this issue.
